platform :ios, '11.0'
target 'JFBaseApp' do
pod 'MJRefresh'
#pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
#pod 'SDCycleScrollView'
#pod 'YTKNetwork'
pod 'QMUIKit'
pod 'SDWebImage', '~>3.8'
pod 'IQKeyboardManager'
#pod 'SGPagingView'
end

